- name: Install docker
  gather_facts: false
  hosts: jenkins

  tasks:
    - name: Install yum utils
      yum:
        name: yum-utils
        state: latest

    - name: Install device-mapper-persistent-data
      yum:
        name: device-mapper-persistent-data
        state: latest

    - name: Install lvm2
      yum:
        name: lvm2
        state: latest

    - name: Add Docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
      become: yes

    - name: Install Docker
      package:
        name: docker-ce
        state: latest
      become: yes

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
      become: yes

    - name: Install docker-py
      package:
        name: python-docker-py
        state: latest
      become: yes

    - name: upload the site directory to the docker host
      copy: src=Dockerfile dest=/tmp/Dockerfile

    - name: Build Docker image from Dockerfile
      docker_image:
        name: gopac/first_web
        path: /tmp
        state: present

    - name: Running the container
      docker_container:
        name: webnode
        image: gopac/first_web:latest
        published_ports: 3000:3000
        state: started
        detach: yes
