- name: Ping Precheck
  gather_facts: false
  hosts: jenkins

  tasks:
    - ping:
    - wait_for:
        port: "{{ item }}"
        state: started         # Port should be open
        delay: 0               # No wait before first check (sec)
        timeout: 3             # Stop checking after timeout (sec)
      with_items:
        - 22
        - 5984
        - 3000
